### ISSUE TITLE
Create free-boundary equilibrium solver

### ISSUE THREAD

**Issue by bclyons12** [ProjectTorreyPines/FUSE.jl#558]
For proper coupling to TokSys, we're looking into making a free-boundary equilibrium solver. The actually PDE solves of this are straightforward, but the tricks come in the multi-loop interations. Details here: [Jardin_free-boundary.pdf](https://github.com/ProjectTorreyPines/FUSE.jl/files/15194800/Jardin_free-boundary.pdf)

**Comment by orso82** [comment]
FRESCO!
