### ISSUE TITLE
Host presentations on website

### ISSUE THREAD

**Issue by bclyons12** [ProjectTorreyPines/FUSE.jl#734]
We should make a **Publications and Presentations** tab on the website that can be continuously updated. We've got the arXiv paper and Tim's talk already, but we could put all of the APS posters on there for people to freely access.

**Comment by orso82** [comment]
Excellent idea! I'll get that going soon

**Comment by orso82** [comment]
please upload your APS posters/presentations here: https://github.com/ProjectTorreyPines/FUSE_extra_files/tree/master/APS2024

**Comment by bclyons12** [comment]
@TimSlendebroek @adrianaghiozzi @ggdose @tomneiser
See Orso's comment above

**Comment by TimSlendebroek** [comment]
> @TimSlendebroek @adrianaghiozzi @ggdose @tomneiser See Orso's comment above

done
