### ISSUE TITLE
Correct function of ITER VS coils

### ISSUE THREAD

**Issue by bclyons12** [ProjectTorreyPines/FUSE.jl#738]
Currently if you do `dd, ini, act = FUSE.init(:ITER, init_from=:ods)`, the last two active coils are labeled as shaping coils, i.e., `dd.pf_active.coil[end].function[1].index` is 1. Those indices should be 2 instead for vertical force balance. This will prevent ActorEquilibrium from updating the current in those coils to make the shape.

**Comment by orso82** [comment]
@bclyons12 please try with the latest `IMAS#master`
