### ISSUE TITLE
A mismatch between `grid.dim2` and the size of `psi` in `tequila2imas` function

### ISSUE THREAD

**Issue by mgyoo86** [ProjectTorreyPines/FUSE.jl#768]
# Issue in `profiles_2d[1]` (flux coordinate)

## A Mismatch Between `grid.dim2` and the Size of `psi` 

In the following example, `dim2` is set to 21, but the second dimension of `psi` (`size(psi, 2)`) is 13.

![Screenshot 2024-11-20 at 11 43 24 AM](https://github.com/user-attachments/assets/cd8b6dd6-a1ad-4aa0-83ed-ad488a209b1b)

# Cause of the Issue

The following code block in the `tequila2imas` function defines `dim2`:

https://github.com/ProjectTorreyPines/FUSE.jl/blob/605a7ef0e98e76b81b986ec9d59986b6fa1a6716/src/actors/equilibrium/tequila_actor.jl#L187-L192

In this code block, `shot.M` (which corresponds to `number_of_fourier_modes` (default=8) in the `ActorTEQUILA` parameters) is used to define `dim2`. 

However, the size of `psi` is determined by `number_of_MXH_harmonics` (default=4), resulting in 13 components in the second dimension. (where 13 components = 5 basic terms + 4 cos terms + 4 sin terms).

# Questions

- What is the difference between `number_of_fourier_modes` and `number_of_MXH_harmonics` in the `FUSEparameters__ActorTEQUILA`? Do they have different applications?
- What are the correct definitions for `dim2` and the second dimension of `psi`?

**Comment by mgyoo86** [comment]
@bclyons12 @orso82 Could you please take a look at this issue when you have time? Thank you very much.

**Comment by bclyons12** [comment]
I opened a bug fix for this, but you should test it on your case by changing your FUSE branch to that one and rerunning ActorEquilibrium/ActorTEQUILA.

Answers to your questions:

- _What is the difference between number_of_fourier_modes and number_of_MXH_harmonics in the FUSEparameters__ActorTEQUILA? Do they have different applications?_
  - `number_of_MXH_harmonics` is the number of shape harmonics used by TEQUILA in flux surface fitting. 
  - `number_of_fourier_modes` is the number of Fourier modes used in the representation of `Psi(rho, theta)`. As TEQUILA converges, the poloidal variation in the flux should converge away, but internally, it needs those degrees of freedom to find the solution.
- What are the correct definitions for dim2 and the second dimension of psi?
  - It should be `number_of_MXH_harmonics`. That number isn't stored in TEQUILA anywhere, so we take its length from the surfaces array. I could make a convenience function in TEQUILA to provide this in the future.

**Comment by mgyoo86** [comment]
@bclyons12 Thank you very much for the quick fix!  I will test it and keep you updated.
